### ISSUE TITLE
[Bot/Bug]: Often Disconnects on my bots

### ISSUE THREAD

**Issue by Hausi1980** [MinecraftBot-com/MineBot-V3-Issues#65] opened 2024-09-25 18:50 UTC
### Current Behavior

Hello, 

my bots often disconnect from the server very often. I send screenshots with the error messages. 

I am online with my main account all day - i have no connection issues with my client. 

### Screenshots

![image](https://github.com/user-attachments/assets/fd041bef-7999-4b30-b8bf-dd0512866007)

### Profile/Snapshot

Reporting user support id: -

Reporting profile id: -

Profile snapshot: -

**Comment by Hausi1980** [comment] 2024-09-25 18:56
![image](https://github.com/user-attachments/assets/98f69e27-3620-4c1e-b924-b2d2040c2eef)

**Comment by OnlyQubes** [comment] 2024-10-08 20:55
Duplicate of #68

**Closed as not planned by OnlyQubes** 2024-10-08 20:55 UTC
